### ISSUE TITLE
Naming of arguments in interp1d_unc is not aligned with scipy

### ISSUE THREAD

**Issue by eichstaedtPTB** [PTB-M4D/PyDynamic#109]
Suggest that `PyDynamic.uncertainty.interpolation.interp1d_unc` naming and documentation of method arguments be aligned with the corresponding scipy method, because it is not only for time domain calculations.

**Comment by BjoernLudwigPTB** [comment]
> Suggest that `PyDynamic.uncertainty.interpolation.interp1d_unc` naming and documentation of method arguments be aligned with the corresponding scipy method, because it is not only for time domain calculations.

If I get this right, you would suggest the following signature

```python
interp1d_unc(x, y, uy, kind='linear')
```

and then cite the docstring of [scipy.interpolate.interp1d](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html#scipy-interpolate-interp1d) for the provided parameters?

**Comment by BjoernLudwigPTB** [comment]
Although this is kind of cosmetical, it actually breaks the original signature, which means a BREAKING CHANGE. I would suggest to introduce this change with the major release resulting from the module renaming from #31 .
