### ISSUE TITLE
Proposal: support for resampling/upsampling in GUM_iDFT

### ISSUE THREAD

**Issue by bruns01** [PTB-M4D/PyDynamic#15]
The method GUM_iDFT has a parameter Nx=... which is meant to represent the requested number of samples in the time domain. However, in the current implementation this is limited by the number of frequencies available. Hence, upsampling of a band limited signal is not possible for now.
Subsequently applied scipy.signal.resample() calls will again operate in the frequency domain using fft and ifft. 
Therefore it seems reasonable to include an upsampling option in GUM_iDFT.

**Comment by bruns01** [comment]
The manual for np.fft.irfft states:
<cite>
n : int, optional
    Length of the transformed axis of the output. For n output points, n//2+1 input points are necessary. If the input is longer than this, it is cropped. If it is shorter than this, it is padded with zeros. If n is not given, it is determined from the length of the input along the axis specified by axis.
</cite>
Hence, upsampling is possible with irfft, already. Or do I read this wrong?

**Comment by eichstaedtPTB** [comment]
First step: Identify exact method in np.fft.irfft for this and derive the formula/equation for corresponding uncertainty treatment

**Comment by BjoernLudwigPTB** [comment]
@mgrub As #311 is merged and released, this one should be closed as well, right?

**Comment by BjoernLudwigPTB** [comment]
And finally it is released in [v2.4.0](https://twitter.com/ptb_m4d/status/1637754389921185793).
