### ISSUE TITLE
Extend IIRuncFilter() to colored noise inputs

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [PTB-M4D/PyDynamic#154]
The function *`IIRuncFilter`* in _`uncertainty.propagate_filter`_ does currently only work for white noise input signals. The corresponding paper also applies for colored noise. In addition, that the output can be covariance matrix needs to be addressed. Currently it's only point-wise standard deviations.

This is dealt with in #95

**Comment by BjoernLudwigPTB** [comment]
We check if this is resolved already. If it is not, we will exclude it from the major release and possibly develop it as a feature later.

@mgrub Can you say more to this?

**Comment by mgrub** [comment]
The re-implemented `IIRuncFilter` in [the prepare 2.0.0 branch](https://github.com/PTB-PSt1/PyDynamic/blob/prepare_major_release_2.0.0/PyDynamic/uncertainty/propagate_filter.py#L216) can be used for correlated noise by setting its keyword `kind="corr"` and interpreting `Ux` as single-sided stationary autocovariance. 

However, this implementation is not available in the master-branch, yet. (As the naming of input parameters will change)
