### ISSUE TITLE
Increase threshold for test_ARMA

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [PTB-M4D/PyDynamic#279]
Apparently one of the tolerances in our test suite for checking `ARMA()` is too strict. See some of the most recent failed instances:

- https://app.circleci.com/pipelines/github/PTB-M4D/PyDynamic/2711/workflows/666c9563-ff15-4b60-892a-9d4380271275/jobs/14973/tests#failed-test-0
- https://app.circleci.com/pipelines/github/PTB-M4D/PyDynamic/2711/workflows/666c9563-ff15-4b60-892a-9d4380271275/jobs/14975/tests#failed-test-0
- https://app.circleci.com/pipelines/github/PTB-M4D/PyDynamic/2709/workflows/c4768521-6f49-4295-addc-1ec2fd4162b1/jobs/14961/tests#failed-test-0
- https://app.circleci.com/pipelines/github/PTB-M4D/PyDynamic/2705/workflows/9c5f9554-7840-449b-8ab1-85d7f2570dde/jobs/14938/tests#failed-test-0
 
It looks like we should increase to a value of `atol = 0.22`. The line above that assertion fails less often, but the following failed instance suggests to raise the tolerance for that as well:

- https://app.circleci.com/pipelines/github/PTB-M4D/PyDynamic/2704/workflows/164c507d-354e-441d-a5ea-d940d5e1d907/jobs/14929/tests#failed-test-0

Seems as if `rtol = 0.22` might be a good choice as well.

**Comment by mgrub** [comment]
Alright, thanks for the hint. I dived into this and produced a plot showing our options. It shows the fluctuation of the `std`-estimator by evaluating random arrays of different length multiple times (there is some theory about this out there, like https://web.eecs.umich.edu/~fessler/papers/files/tr/stderr.pdf , but a MonteCarlo-sim was easier to code and visualize ). 

![std_estimator_randn](https://user-images.githubusercontent.com/50821607/161735428-6945ae43-5b22-4238-9893-32aa4423aeab.png)

I would therefore suggest to either:
- set `atol=0.25` (as `y==1.0`, `atol` and `rtol` are practically the same, or
- increase the array length to `140` (or more)
- 
(I would opt for the adjusted tolerance, as a longer array also means more computational load.)

**Comment by mgrub** [comment]
Moreover, the tolerance of the `assert_allclose(np.mean(w), 0.0, atol=0.2)` in the next line is also likely to fail, as a similiar plot for the mean-estimator suggest:

![mean_estimator_randn](https://user-images.githubusercontent.com/50821607/161736811-8922f3a6-7a1e-4e36-bed0-5a77e82bef74.png)

Here, I would suggest to
- set `atol=0.35`, or
- increase the array length to `280` (or more)

**Comment by BjoernLudwigPTB** [comment]
Thanks for the thorough investigation! That shoul do and actually inspired me to take a similar appoach for another occasionally failing test. Nice one! Changes already approved…
