### ISSUE TITLE
Optionally return RMS-value of LSIIR

### ISSUE THREAD

**Issue by mgrub** [PTB-M4D/PyDynamic#288]
**Is your feature request related to a problem? Please describe.**
LSIIR is able to print an rms-value if the verbose-flag is given. However, the value stays internal and is not available for later use. 

**Describe the solution you'd like**
Add a `return_rms`-flag to LSIIR to enable an additional return value. 
The default should be `return_rms=False`, to keep backwards compatibility. 

**Additional context**
Based on the rms-value, the output of multiple runs of LSIIR (e.g. with different coefficient lengths) can be compared automatically.

**Comment by BjoernLudwigPTB** [comment]
From [v2.3.0](https://github.com/PTB-M4D/PyDynamic/releases/tag/v2.3.0) on it is now possible to call LSIIR with [a new parameter `return_rms=True`](https://pydynamic.readthedocs.io/en/v2.3.0/PyDynamic.model_estimation.html#PyDynamic.model_estimation.fit_filter.LSIIR) to receive an additional float, which specifies the [root-mean-square](https://en.wikipedia.org/wiki/Root_mean_square), e.g.:

```python
[…]
b, a, tau, Uab, rms = LSIIR(H, Nb, Na, f, Fs, return_rms=True)
```
Let us know what you think of it and if it works for you.
