### ISSUE TITLE
Requirements to run src/PyDynamic/examples

### ISSUE THREAD

**Issue by mgrub** [PTB-M4D/PyDynamic#307]
There are two locations for the PyDynamic-tutorials: one in this repository [1] and one separate repository [2].
When installing only the default requirements [3], it seems like the jupyter-examples in `PyDynamic/src/PyDynamic/examples` cannot be executed because of missing dependency (likely `notebook`). 

Jupyter/ipython/notebook is only mentioned in the dev-requirements of PyDynamic. 

I would like to discuss whether:

- to include `notebook` (and maybe others) into the default requirements, but with an optional flag
- move the remaining jupyter-examples in [1] to [2]

[1] <https://github.com/PTB-M4D/PyDynamic/tree/main/src/PyDynamic/examples>
[2] <https://github.com/PTB-M4D/PyDynamic_tutorials>
[3] <https://github.com/PTB-M4D/PyDynamic/blob/main/requirements/requirements-py310.txt>

**Comment by BjoernLudwigPTB** [comment]
I strongly agree, that we should merge the notebooks into [2]. I do not think, that this will be much work. It simply was never important enough. If there is some urge now to unify the tutorials, we should do so.
Still, to resolve your current dependency issue, we have [a section in the INSTALL.md](https://github.com/PTB-M4D/PyDynamic/blob/main/INSTALL.md#optional-jupyter-notebook-dependencies) about how to install the optional dependency (`notebook`) for the examples.

**Comment by BjoernLudwigPTB** [comment]
Thus, if I understand correctly there is no bug here, why I would suggest to remove the bug label and maybe add `cosmetics` and/or `documentation`.

**Comment by BjoernLudwigPTB** [comment]
@mgrub What do you say to my last two comments?

**Comment by mgrub** [comment]
Sorry for the delay! Thanks for the reference to the `INSTALL.md`, I must have missed that. I think, we can leave it as it is.
