### ISSUE TITLE
Allow zero uncertainty of filter-parameters in IIRuncFilter

### ISSUE THREAD

**Issue by mgrub** [PTB-M4D/PyDynamic#49]
In [uncertainty.propagate_filter.IIRuncFilter](https://github.com/eichstaedtPTB/PyDynamic/blob/master/PyDynamic/uncertainty/propagate_filter.py#L96) allow to have zero uncertainty of filter-parameters. 

Remark:
- task seems obsolet, uncertainty `Uy` takes full account of changes in `Uab`, as published in equation 12 of [the associated paper](http://dx.doi.org/10.1088/0957-0233/20/5/055104)
- modifications/variations of `Uab` in [IIR-example](https://github.com/eichstaedtPTB/PyDynamic/blob/master/examples/Digital%20filtering/uncpropagation_IIR.py) show very good agreement between IIRuncFilter and Monte-Carlo-method - independent of `Uab` being zero or not.

<br/><br/>

Output with `Uab != 0`
![uncertainty_not_equal_zero](https://user-images.githubusercontent.com/50821607/59498905-95255080-8e96-11e9-9e48-ef1a714229cc.png)
 
<br/><br/>

Output with `Uab == 0`
![uncertainty_equal_zero](https://user-images.githubusercontent.com/50821607/59498904-948cba00-8e96-11e9-8266-d7ea9e25ba22.png)

<br/><br/>

Issue generated from in-code-TODO, see #41

**Comment by eichstaedtPTB** [comment]
This TODO actually meant to optimize the code for the case that `Uab` is zero, starting by rewriting the function call as `IIRuncFilter(x,noise, b, a, Uab=None)`. 
The function code itself should fall back to a more efficient calculation of `Uy` for the case that `Uab` is zero.

**Comment by BjoernLudwigPTB** [comment]
Will be resolved by #95
