### ISSUE TITLE
Reintroduce previously not used parameter wt in LSFIR_uncMC

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [PTB-M4D/PyDynamic#66]
We removed a parameter `wt` from the following [method signature](https://github.com/PTB-PSt1/PyDynamic/blob/bc31e98a569fe657ad3be7356f2a75cda1485ab1/PyDynamic/deconvolution/fit_filter.py#L226) but the parameter should actually be used in the implementation. We should therefore reintroduce the parameter to the signature and implement the weights.

The docstring stated:

> ` wt: np.ndarray of shape (2M,), optional
             vector of weights`

**Comment by eichstaedtPTB** [comment]
Definitely necessary. In principle, it should suffice to add
```Python
X = np.dot(np.diag(wt), X)
```
similar to LSFIR_unc.

**Comment by eichstaedtPTB** [comment]
Additionally, error checking the wt vector should be included as in LSFIR_unc.
